### ISSUE TITLE
Bilderbeispiele für Postkarten hinterlegen

### ISSUE THREAD

**Issue by suchmaske** [telota/quoteSalute#15]
Auf Github kann man nicht direkt sehen, wie die Postkarten aussehen, da es Adobe Illustrator Dateien sind. Es wäre gut wenn für jedes Template auch noch eine JPG/PNG-Version mit hochgeladen werden könnte.

**Comment by Rein3ke** [comment]
Done!

**Comment by suchmaske** [comment]
Danke
