### ISSUE TITLE
Kleiner Fehler im Datenbestand

### ISSUE THREAD

**Issue by StefanDumont** [telota/quoteSalute#21]
»Berlin, den 7. Januar 1919« -  Lebenswelten, Erfahrungsräume und politische Horizonte der ostpreußischen Adelsfamilie Lehndorff vom 18. bis in das 20.Jahrhundert
Rechtsanwalt Siebert an Carol Graf von Lehndorff . Berlin, 7. Januar 1919

**Comment by lauml** [comment]
gelöscht.
