### ISSUE TITLE
Dokumentation ergänzen / korrigieren

### ISSUE THREAD

**Issue by StefanDumont** [telota/quoteSalute#22]
* Im Readme unter der Dokumentation sollte die aktuelle Anzahl der aggregierten Grußformeln stehen
* Das Readme sollte die Lizenzierung von App und Daten präziser trennen. Derzeit scheint es so, als wäre die BBAW Copyright-Inhaberin der Daten. Man könnte etwa einen zusätzlichen Abschnitt "Lizenzen Dritter" einfügen, der vllt. auch alle verwendeten Daten einmal genau listet (bei der Gelegnheit auch "Lizenz" statt "Licence").

**Comment by lauml** [comment]
Habe in der Doku neuen Unterpunkt bei Korpus für die Lizenzen hinzugefügt und im Readme drauf verwiesen.

**Comment by StefanDumont** [comment]
Ich würde die Lizenzangaben einfach in Klammern hinter den Korpus setzen (lizenziert unter ...), dann wiederholt sich das nicht so. Und die jeweilige Lizenz noch zusätzlich verlinken. Unsere Lizenz würde ich in der Doku ganz ans Ende setze.  Schlussendlich würde ich den Abschnitt von der Readme aus verlinken :-)

**Comment by lauml** [comment]
so jetzt sollte es besser sein

**Comment by StefanDumont** [comment]
Perfekt!
